       {const providers = {};
providers.local = new Scaffolding.Cloud.LocalStorageProvider("cloudvariables:9999");
providers.ws = new Scaffolding.Cloud.WebSocketProvider("wss://kewllab-server.herokuapp.com", "9999");
for (const provider of Object.values(providers)) scaffolding.addCloudProvider(provider);
scaffolding.addCloudProviderOverride("☁ torso costume name", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ head costume name", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ local storage password", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ local storage username", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ accounts from server local", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ games from server local", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ secured gm local", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ secured ac local", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ graphics mode", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ open link", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ hat costume", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ eval", providers[""] || null);
scaffolding.addCloudProviderOverride("☁ account data secured", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ last log in", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ amoc", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ rain intensity", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ redirect", providers[""] || null);
scaffolding.addCloudProviderOverride("☁ item animations shown", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ collected from box", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ icon", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ forums data secured", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ forums data public", providers[""] || null);
scaffolding.addCloudProviderOverride("☁ forum request", providers[""] || null);
scaffolding.addCloudProviderOverride("☁ pixel accuracy", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ shadows on?", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ effect name", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ code sync", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ sync state", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ custom color offset", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ eval output", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ render scale", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ crates local", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ crates timer", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ steps today", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ playtime today", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ jumps today", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ quests", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ high quality?", providers["local"] || null);
scaffolding.addCloudProviderOverride("☁ Data from server", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ Requesting client id", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ Can update local players?", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ Can update clone position", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ chat request", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ accounts", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ Players inventory data", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ is server online?", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ server games", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ account from a client", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ can check data local?", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ game server secured games", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ game from a client", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ Data from client 2", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ Data from client 3", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ account server secured accounts", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ Data from client 1", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ latest version", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ item request client", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ accounts data public", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ news1", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ news2", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ news3", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ server counter", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ game request from client", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ lenght of game page", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ account request from client", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ character data request", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ character data", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ crates", providers["ws"] || null);
scaffolding.addCloudProviderOverride("☁ crates request", providers["ws"] || null);
};
